## Dockerfile-test

FROM silex/emacs:27.1-ci-cask

ENV HOME=/root

RUN which cask
RUN which python
RUN python --version
RUN git clone https://github.com/pyenv/pyenv.git $HOME/.pyenv

ENV PATH=$HOME/.pyenv/bin:$PATH
RUN eval "$(pyenv init -)"

ENV DEBIAN_FRONTEND=noninteractive

# https://github.com/pyenv/pyenv/wiki#suggested-build-environment
RUN apt-get update

RUN apt-get install --no-install-recommends -y \
    make build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev \
    xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

RUN pyenv install 3.8.6
RUN pyenv global 3.8.6
