## test.yml

name: Main workflow
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '25.1'
          - '25.2'
          - '25.3'
          - '26.1'
          - '26.2'
          - '26.3'
          - '27.1'
          - 'snapshot'
        include:
          - emacs_version: 'snapshot'
            allow_failure: true
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: conao3/setup-cask@master

    - name: Python version
      run: |
        which pip
        which pip3
        python --version
        python3 --version

    - name: Prepare environment
      run: |
        pip install pipenv
        mkdir existing-project
        cd existing-project
        pipenv --python 3
        cd ../

    - name: Run tests
      if: matrix.allow_failure != true
      run: 'make test'

    - name: Run tests (allow failure)
      if: matrix.allow_failure == true
      run: 'make test || true'

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: purcell/setup-emacs@master
      with:
        version: '27.1'
    - uses: conao3/setup-cask@master

    - name: Run lint
      run: 'cask && make lint'
